"use client";

import Image from "next/image";
import { useState } from "react";
import { Eyebrow, Icon, PrimaryLink } from "./ui";

const dogImage = "/stitch/assets/AB6AXuCUBtQfpQ2XpoZRsdc0iQynkuH5IMjA7Jl22ODmvFa--N2CTviER8aROAtaaFibHNLMRsR2HwXviORGHTFGv8wQlOzbNTlX-be7b0a41a0bdc1c506b2b0bc4b0961b3";

export function ProfitCallout() {
  return <section className="mx-auto w-full max-w-[1440px] px-margin-mobile py-space-2xl md:px-margin"><div className="flex flex-col items-center justify-between gap-space-lg rounded-3xl bg-surface-container-high p-space-xl md:flex-row md:p-space-2xl"><div className="max-w-2xl"><Eyebrow>Diferencial Essencial</Eyebrow><h2 className="mb-space-sm text-headline-lg-mobile font-extrabold md:text-headline-lg">Faturar é importante. Saber quanto sobra é essencial.</h2><p className="mb-space-md text-body-lg text-on-surface-variant">O Flux Pet mostra o faturamento, os custos, a margem e o lucro do seu negócio em tempo real. Pare de adivinhar o resultado no extrato bancário.</p><PrimaryLink>Quero conhecer</PrimaryLink></div><div className="w-full shrink-0 rounded-2xl bg-surface-container-lowest p-space-lg shadow-md md:w-80"><div className="flex items-center justify-between"><strong className="text-label-md">Demonstrativo Sintético</strong><Icon className="text-[20px] text-primary-container">analytics</Icon></div><div className="space-y-2 pt-4 text-body-sm">{[["(+) Faturamento Bruto","R$ 32.480"],["(-) CMV & Fornecedores","- R$ 19.820"],["(-) Custos Fixos & Operação","- R$ 5.820"]].map(([label,value]) => <div className="flex justify-between" key={label}><span className="text-on-surface-variant">{label}</span><strong>{value}</strong></div>)}<div className="flex justify-between rounded-lg bg-surface-container-low p-2 text-title-md font-bold text-primary-container"><span>(=) Sobra Real</span><span>R$ 6.840</span></div></div></div></div></section>;
}

const inventory = [
  ["warehouse", "Equilibrado", "Estoque Atual", "R$ 54.200", "Total avaliado em prateleira. 1.420 SKUs monitorados e catalogados com margens calculadas."],
  ["warning", "3 Alertas", "Estoque Crítico", "12 itens", "Produtos com menos de 3 dias de cobertura de venda. Sugestão automática de compras gerada."],
  ["hourglass_empty", "Ação sugerida", "Produtos Parados", "R$ 3.890", "Capital parado há mais de 45 dias sem giro. Ideais para liquidações relâmpago ou combos promocionais."],
] as const;
const lines = [["pets", "Ração Premium Porte Médio 15kg", "8 un em estoque"], ["medication", "Antipulgas & Carrapatos 10-20kg", "2 un (Crítico)"], ["local_mall", "Areia Higiênica Biodegradável 4kg", "44 un em estoque"]] as const;

export function Inventory() {
  return <section className="w-full bg-surface-container-low py-space-2xl"><div className="mx-auto max-w-[1440px] px-margin-mobile md:px-margin"><div className="mb-space-xl max-w-2xl"><Eyebrow>Controle sem desperdício</Eyebrow><h2 className="text-headline-lg-mobile font-extrabold md:text-headline-lg">Estoque parado também é dinheiro.</h2><p className="mt-2 text-body-lg text-on-surface-variant">Saiba o que vende, o que está parado e o que precisa ser reposto imediatamente.</p></div><div className="mb-space-xl grid gap-space-lg md:grid-cols-3">{inventory.map(([icon,badge,title,value,copy]) => <article className="rounded-2xl bg-surface-container-lowest p-space-lg shadow-sm" key={title}><div className="mb-space-sm flex items-center justify-between"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary-fixed text-primary"><Icon>{icon}</Icon></span><span className="rounded-full bg-primary-fixed px-2 py-0.5 text-label-sm font-bold">{badge}</span></div><h3 className="text-headline-sm font-bold">{title}</h3><p className="my-1 text-display-lg font-extrabold">{value}</p><p className="text-body-sm text-on-surface-variant">{copy}</p></article>)}</div><div className="rounded-2xl bg-surface-container-lowest p-space-lg shadow-sm"><p className="mb-space-md flex items-center gap-2 text-title-md font-bold"><Icon className="text-primary">checklist</Icon>Monitoramento em Tempo Real de Linhas Críticas</p><div className="grid gap-space-md md:grid-cols-3">{lines.map(([icon,title,status],index) => <div className="flex items-center justify-between gap-3 rounded-xl bg-surface-container-low p-3" key={title}><div className="flex min-w-0 items-center gap-3"><Icon className="shrink-0 text-primary">{icon}</Icon><div><p className="text-label-md font-bold">{title}</p><p className="text-body-sm text-on-surface-variant">Giro médio: {12 + index * 10} un/semana</p></div></div><span className="shrink-0 rounded-md bg-emerald-100 px-2 py-1 text-label-sm font-bold text-emerald-800">{status}</span></div>)}</div></div></div></section>;
}

const faqs = [["O que é o Flux Pet?", "Um sistema de gestão completo e simples feito sob medida para pet shops controlarem vendas, estoque e finanças em uma tela organizada e sem jargões contábeis complexos."], ["O Flux Pet controla estoque?", "Sim. Acompanhe entradas, saídas, níveis críticos e saiba exatamente quais itens estão parados há mais tempo para planejar compras assertivas e evitar desperdício."], ["Consigo acompanhar meu lucro?", "Sim. O sistema calcula automaticamente CMV, custos e margem para mostrar seu lucro líquido real por dia, semana e mês."], ["Posso emitir nota fiscal?", "Sim, através de integração direta e simplificada com emissores homologados para NFC-e e NF-e."]] as const;

export function FinalCallToAction() {
  const [open, setOpen] = useState(0);
  return <section className="mx-auto w-full max-w-[1440px] px-margin-mobile py-space-2xl md:px-margin" id="quero-conhecer"><div className="mb-space-2xl overflow-hidden rounded-3xl bg-surface-container-high shadow-2xl"><div className="grid items-center lg:grid-cols-12"><div className="relative min-h-[380px] md:min-h-[480px] lg:col-span-6"><Image src={dogImage} alt="Cão labrador tranquilo em um pet shop charmoso" fill sizes="(min-width: 1024px) 50vw, 100vw" className="object-cover" /></div><div className="flex flex-col items-start gap-space-md p-space-xl md:p-space-2xl lg:col-span-6"><span className="inline-flex items-center gap-2 rounded-full bg-primary-fixed px-3 py-1 text-label-sm font-bold uppercase tracking-wider"><Icon className="text-[16px]">favorite</Icon>Cuidado e Controle</span><h2 className="text-headline-lg-mobile font-extrabold md:text-headline-lg">Cuide do seu negócio como você cuida dos seus clientes.</h2><p className="text-body-lg text-on-surface-variant">Tenha uma visão completa do seu pet shop e tome decisões com mais segurança. O Flux Pet foi desenhado para quem ama animais e quer prosperidade sustentável.</p><PrimaryLink>Quero conhecer o Flux Pet</PrimaryLink><p className="text-body-sm text-outline">Demonstração guiada gratuita · Sem necessidade de cartão de crédito no início.</p></div></div></div><div className="mx-auto max-w-3xl pt-space-md" id="faq"><div className="mb-space-xl text-center"><Eyebrow>Tire Suas Dúvidas</Eyebrow><h3 className="text-headline-md font-extrabold">Perguntas Frequentes</h3><p className="mt-1 text-body-md text-on-surface-variant">Tudo o que você precisa saber antes de dar o próximo passo.</p></div><div className="space-y-space-sm">{faqs.map(([question,answer],index) => { const expanded = open === index; return <div className="overflow-hidden rounded-2xl bg-surface-container-low" key={question}><button type="button" aria-expanded={expanded} onClick={() => setOpen(expanded ? -1 : index)} className="flex w-full items-center justify-between gap-4 p-space-md text-left text-title-md font-bold"><span>{question}</span><Icon className={`text-outline transition-transform ${expanded ? "rotate-180" : ""}`}>expand_more</Icon></button>{expanded && <div className="px-space-md pb-space-md text-body-md text-on-surface-variant">{answer}</div>}</div>; })}</div></div></section>;
}
